
export component DashboardPage inherits Rectangle {
    in property <string> welcome_message: "Rivvitium Dashboard";

    width:        100%;
    height:       100%;
    background: #e6f7e0; // Light green

    VerticalLayout {
        alignment: center;
        spacing:   15px;

        Text { text: "Dashboard"; font-size: 32px; font-weight: 700; }
        Text { text: welcome_message;     }
        Text { text: "Here's your data!"; }
    }
}
