// ui/pages/pipeline_page.slint

// Import ALL used standard widgets from "std-widgets.slint"
//
import { StandardButton, LineEdit} from "std-widgets.slint";

export component PipelinePage inherits Rectangle {
    in-out property <string> username: "";
    in-out property <string> password: "";
    callback login_requested(string, string);

    width:        100%;
    height:       100%;
    background: #20f2f7; // Light blue

    VerticalLayout {
        alignment: center;
        spacing:   15px;

        Text     { text: "Pipeline"; font-size: 32px; font-weight: 700; }
        LineEdit { placeholder-text: "Username"; text: root.username; width: 250px; }
        LineEdit { placeholder-text: "Password"; text: root.password; width: 250px; }

        StandardButton {
            kind:      apply;
            clicked => { login_requested(root.username, root.password); }
        }
    }
}
