// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

// export { AboutPage    } from "pages/pages/about_page.slint";
//export { ControlsPage } from "pages/controls_page.slint";
export { ListViewPage } from "pages/list_view_page.slint";
export { TableViewPage, TableViewPageAdapter } from "ui/pages/table_view_page.slint";
export { TextEditPage } from "text_edit_page.slint";
