[package]
name       = "cli"
version    = "0.1.0"
edition    = "2024"

[dependencies]
anyhow      = "1.0"
apex        = {path = "../apex"}
riv         = {path = "../riv"}
zero        = {path = "../zero"}
