[package]
name        = "apex"
version     = "0.1.0"
edition     = "2024"

[dependencies]
riv                = {path = "../riv"}
tracing            = "0.1"
tracing-subscriber = {version = "0.3", features = ["fmt", "env-filter"] }
zed                = {path = "../zed"}
