// ui/about_dialog.slint

import {StandardButton} from "std-widgets.slint";

export component AboutDialog inherits Window { // A dialog is often a Window
    width:    300px;
    height:   150px;
    visible:  false;
    title:     "About Rivvitium";

    // These are standard callbacks that Slint's run_as_dialog() listens for
    callback accepted();
    callback rejected(); // Not used for a simple "About" but good to know

    VerticalLayout {
        padding: 10px;
        alignment: center;
        spacing: 15px;
        Image {
            source:  "file://ui/assets/logos/rivvitium.jpeg";
        }

        Text { text: "Rivvitium"; font-size: 20px; font-weight: 600; }
        Text { text: "Version 0.1.0"; }
        Text { text: "(C) 2025 Reid Turner"; }

        StandardButton {
            kind: ok;
            clicked => {
                root.visible = false;
                root.accepted();
                }    // Call accepted() to close the dialog
        }
    }
}
